const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Behaviors.Flash,
		C3.Behaviors.LOS,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.gamepad,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.shadowcaster,
		C3.Plugins.shadowlight,
		C3.Plugins.Arr,
		C3.Plugins.Tilemap,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.shadowlight.Acts.SetPosToObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.LOS.Cnds.HasLOSToPosition,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.LOS.Acts.ClearObstacles,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Tilemap.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Text.Acts.SetFontColor
	];
};
self.C3_JsPropNameTable = [
	{GreyTileBackGround: 0},
	{Solid: 0},
	{Counter: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{DestroyOutsideLayout: 0},
	{Bullet: 0},
	{Timer: 0},
	{Flash: 0},
	{LineOfSight: 0},
	{EvilBaguette: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Gamepad: 0},
	{Window1: 0},
	{Window2: 0},
	{Audio: 0},
	{Health: 0},
	{Alive: 0},
	{GoodButters: 0},
	{Healthbar: 0},
	{Fridge: 0},
	{KillBox: 0},
	{Sine: 0},
	{HealingApple: 0},
	{Carrotspear: 0},
	{CrackerSpike1: 0},
	{CrackerSpike2: 0},
	{CrackerSpike3: 0},
	{Cookie1: 0},
	{Cookie2: 0},
	{Movement: 0},
	{BreadRoll: 0},
	{BreadrollLimiter: 0},
	{DashUpgrade: 0},
	{SprintUpgrade: 0},
	{DJUpgrade: 0},
	{EJUpgrade: 0},
	{Lemonade: 0},
	{LemonadeUpgrade: 0},
	{LemonadeShrapnel: 0},
	{CheckpointFlag: 0},
	{DreadRollBox: 0},
	{Fade: 0},
	{DreadRoll: 0},
	{BlackScreen: 0},
	{IntroText1: 0},
	{IntroText2: 0},
	{IntroText3: 0},
	{IntroText4: 0},
	{IntroText5: 0},
	{IntroText6: 0},
	{IntroText7: 0},
	{IntroText8: 0},
	{IntroText9: 0},
	{Titlecard: 0},
	{Fire: 0},
	{BarrierBeam1: 0},
	{TutorialText1: 0},
	{TutorialText2: 0},
	{TutorialText3: 0},
	{TutorialText4: 0},
	{TutorialText5: 0},
	{GoodButterTutorialStartBox: 0},
	{GoodButtersbox1: 0},
	{GoodButtersBox2: 0},
	{Direction: 0},
	{YeastBeast: 0},
	{BarrierBeamEmitter1: 0},
	{Pantrybackground1: 0},
	{ShadowCaster: 0},
	{PantryPlatforms: 0},
	{YeastBeastBarrier: 0},
	{YeastBeastRNG: 0},
	{GlazeWaveright: 0},
	{GlazeWaveleft: 0},
	{YeastBeastMines: 0},
	{RightPantryWall: 0},
	{ShadowLight: 0},
	{YeastBeastSpawnTrigger: 0},
	{YeastBeastSpawnBox: 0},
	{HealingAppleDialogueBox: 0},
	{HealingAppleText: 0},
	{LemonadeDialogueBox: 0},
	{LemonadeDialogue: 0},
	{BreadRollDialogueBox: 0},
	{BreadRollDialogue: 0},
	{MeleeDialogueBox: 0},
	{MeleeUpgrade: 0},
	{ButterKnife: 0},
	{MeleeDialogue: 0},
	{Cinemabars: 0},
	{CheckpointflagCutsceneBoc1: 0},
	{CheckpointFlagCutscene1: 0},
	{CFCutscene1Array: 0},
	{MainMenu: 0},
	{ClickBox: 0},
	{PantryMusicTriggerBox: 0},
	{Dead: 0},
	{YouR: 0},
	{Restart: 0},
	{AsparagusCooldown: 0},
	{Asparagus: 0},
	{Arrow: 0},
	{AsparagusTutorialBox: 0},
	{asparagusTutorialText: 0},
	{CheckpointflagCutsceneBoc2: 0},
	{CFCutscene2Array: 0},
	{CheckpointFlagCutscene2: 0},
	{StartButton: 0},
	{MainMenuBlackout: 0},
	{Shelves: 0},
	{BossBlackout: 0},
	{TBCText: 0},
	{TBCRestartText: 0},
	{Crosshair: 0},
	{PickleSpear: 0},
	{PickleSpearUpgrade: 0},
	{butterKnifeUI: 0},
	{LemonadeUI: 0},
	{CheckpointFlagMedical: 0},
	{AsparagusHitbox: 0},
	{VentBackground: 0},
	{XVent: 0},
	{KitchenDecoration1: 0},
	{VentBackground2: 0},
	{VentWalls: 0},
	{CFCutscene3Array: 0},
	{CheckpointflagCutsceneBoc3: 0},
	{CheckpointFlagCutscene3: 0},
	{VentPlatforms: 0},
	{Attack: 0},
	{Tomatoes: 0},
	{TomatoExplosion: 0},
	{CFBooBox: 0},
	{CFCutscene4Array: 0},
	{CheckpointFlagCutscene4: 0},
	{BeatMall: 0},
	{Meateorite: 0},
	{Parmaggedon: 0},
	{ParmaggeddonWallBox1: 0},
	{ParmaggeddonWallBox2: 0},
	{ParmaggeddonWallBox3: 0},
	{ParmaggeddonWallBox4: 0},
	{ParmaggeddonWallBox5: 0},
	{ParmaggeddonWallBox6: 0},
	{ParmaggeddonWhipHitbox: 0},
	{ParmaggeddonWhipActivationBox: 0},
	{Active: 0},
	{Slippy: 0},
	{MainaraSlipNSlide: 0},
	{ParmaggeddonBFToggle: 0},
	{Turnable: 0},
	{RNGTomato: 0},
	{Meatball: 0},
	{MeatBallLimiter: 0},
	{MeatballExplodybox: 0},
	{Parmpowda1: 0},
	{Parmpowda2: 0},
	{Parmpowda3: 0},
	{MeateoriteSpawn: 0},
	{ParmaggedonSpawnBox: 0},
	{CFCutscene5Array: 0},
	{CheckpointFlagCutscene5: 0},
	{VentPlatformsboss: 0},
	{VentWallsboss: 0},
	{Window3: 0},
	{Pea1: 0},
	{Pea2: 0},
	{Pea3: 0},
	{Level2ToggleBox: 0},
	{Level3ToggleBox: 0},
	{CrackRollEncounterArray: 0},
	{CrackRollCutsceneToggleBox: 0},
	{CrackRollEncounterCutscene: 0},
	{CheckpointFlagCutsceneBoc6: 0},
	{CFCutscene6Array: 0},
	{CheckpointFlagCutscene6: 0},
	{UpgradeWhiteout: 0},
	{LemonadeTooltipText: 0},
	{MeleeTooltipText: 0},
	{DashToolTipText: 0},
	{DoubleJumpToolTipText: 0},
	{EnhancedSprintJumpToolTipText: 0},
	{ShortVent: 0},
	{LongVent: 0},
	{CircleVents: 0},
	{RealWater: 0},
	{SinkLeft: 0},
	{SinkMiddle: 0},
	{SinkRight: 0},
	{SinkCrack1: 0},
	{SinkCrack2: 0},
	{SinkCrack3: 0},
	{SinkDivider: 0},
	{SinkBackground: 0},
	{Guck: 0},
	{Meatloaf: 0},
	{PileofPlates: 0},
	{Plate: 0},
	{CheckpointFlagYeastBeastAftermath: 0},
	{CheckpointFlagParmaggeddonAftermath: 0},
	{YeastbeastaftermathTPbox: 0},
	{CFYeastBeastAftermathArray: 0},
	{CheckpointFlagYeastBeastAftermathCutscene: 0},
	{BaguetteParmSpawnBox: 0},
	{ParmaggeddonaftermathTPbox: 0},
	{CFParmaggeddonAftermathArray: 0},
	{CheckpointFlagPArmaggeddonAftermathCutscene: 0},
	{BossBlackoutParm: 0},
	{CheckpointFlagCrackrollCutsceneboc: 0},
	{CFCRCutsceneArray: 0},
	{CheckpointFlagCrackrollCutscene: 0},
	{HomelanderEyes: 0},
	{CrackRocks: 0},
	{Bite: 0},
	{Clones: 0},
	{SmokeBomb: 0},
	{BouncyBall: 0},
	{UniqueAttack: 0},
	{Fireing: 0},
	{Jumping: 0},
	{Biting: 0},
	{CrackRoll: 0},
	{CrackrollSpawnBox: 0},
	{CrackrollBosfightTpBox: 0},
	{BossBlackoutCrackRoll: 0},
	{Pin: 0},
	{CrackRollLimiter: 0},
	{HomelanderEyesSpit: 0},
	{CrackRock: 0},
	{CrackRollClone1: 0},
	{CrackRollClone2: 0},
	{CrackRollClone3: 0},
	{CrackRollPhase2SpawnBox: 0},
	{CrackRollSmokeBomb: 0},
	{CrackAftermathCutsceneToggleBoc: 0},
	{CrackAftermathCutsceneTPBoc: 0},
	{CrackAftermathCutsceneTPForCrackBoc: 0},
	{CFCrackRollAftermathArray: 0},
	{CheckpointFlagCrackrollaftermathCutscene: 0},
	{CheckpointFlagCRCutscene: 0},
	{Oven: 0},
	{GoodButtersDed: 0},
	{CheckpointFlagCutsceneBoc7: 0},
	{CFCutscene7Array: 0},
	{CheckpointFlagCutscene7: 0},
	{BreadNoughtObjective: 0},
	{PickleSpearUI: 0},
	{PickleSpearTooltipText: 0},
	{CrackRock2: 0},
	{CrackRock3: 0},
	{Window4: 0},
	{Level4Limiters: 0},
	{YeastBeastHealthBAar: 0},
	{ParmaggeddonHealthBar: 0},
	{CrackRollHealthBar: 0},
	{Toaster: 0},
	{AsbestosCrunch: 0},
	{ReadyToFire: 0},
	{SpringBean: 0},
	{Bean: 0},
	{Cutscene1: 0},
	{Cutscene1Black: 0},
	{Cutscene1Black2: 0},
	{Cutscene1Black3: 0},
	{Cutscene1Black4: 0},
	{Cutscene1Black5: 0},
	{Cutscene1Black6: 0},
	{Cutscene1Blackout: 0},
	{BreadNaughtPiece1: 0},
	{BreadNaughtPiece2: 0},
	{BreadnaughtPiece3: 0},
	{BreadnaughtPiece4: 0},
	{BossBlackoutBreadNaught: 0},
	{BreadNaughtTPBox: 0},
	{SinkWater: 0},
	{BreadNaught: 0},
	{FridgeBreadNaught: 0},
	{BreadNaughtMiniguns: 0},
	{BreadNaughtMinigunBullet: 0},
	{BreadNaughtAmmoCounter: 0},
	{BreadNaughtMissileLauncher: 0},
	{BreadNaughtMissile: 0},
	{BreadNaughtCrosshair: 0},
	{BreadNaughtMissleTracker: 0},
	{CrackRollPhase2: 0},
	{BossBlackoutDreadRoll: 0},
	{CheckpointFlagDRCutscene: 0},
	{BreadnaughtDreadrollTpBox: 0},
	{CrackRollDreadrollTpBox: 0},
	{DreadRollSpawnBox: 0},
	{CFCutscene8Array: 0},
	{Level4EndTPBox: 0},
	{CheckpointFlagCutscene8: 0},
	{CFCutscene9Array: 0},
	{CheckpointFlagCutscene9: 0},
	{CheckPointFlagCutsceneBoc8: 0},
	{BossBlackoutBreadnaught2: 0},
	{CrackRollPhase2ded: 0},
	{CheckpointFlagCutscene10: 0},
	{CFCutscene10Array: 0},
	{BossBlackoutDreadRoll2: 0},
	{Tentacles: 0},
	{DreadIntensifies: 0},
	{DreadROLL: 0},
	{FlagWave: 0},
	{DreadPunch: 0},
	{ShardsOfAForbiddenNightmare: 0},
	{DeadmansGraveyard: 0},
	{DreadRollBoss: 0},
	{DreadTenacles: 0},
	{DreadRollDREAD: 0},
	{DreadRollPhaseProgress: 0},
	{DreadRollShardSpawnBox: 0},
	{DreadShard: 0},
	{FIN: 0},
	{ENDBLACK: 0},
	{CrackerSpikes: 0},
	{Cookies: 0},
	{DashReady: 0},
	{Dashing: 0},
	{Spear: 0},
	{Sprint: 0},
	{StrongJump: 0},
	{Lemonadeupgrade: 0},
	{LemonadeReady: 0},
	{ControlledAim: 0},
	{APressed: 0},
	{DPressed: 0},
	{WPressed: 0},
	{LeftClickPressed: 0},
	{YeastBeastAttack: 0},
	{YeastBeastCharge: 0},
	{YeastBeastJumpMines: 0},
	{YeastBeastHealth: 0},
	{YeastBeastIsAlive: 0},
	{YeastbeastBossfight: 0},
	{MeleeReady: 0},
	{CFCutsceneYBaftermath: 0},
	{CFCutscenePaftermath: 0},
	{CFCutsceneCaftermath: 0},
	{CFCutscene1: 0},
	{CFCutscene2: 0},
	{CFCutscene3: 0},
	{CFCutscene4: 0},
	{CFCutscene5: 0},
	{CFCutscene6: 0},
	{CFCutscene7: 0},
	{CFCutscene8: 0},
	{CFCutscene9: 0},
	{CFCutscene10: 0},
	{CRCutscene: 0},
	{DRCutscene: 0},
	{CRBossCutscene: 0},
	{InCutsceneYBAftermath: 0},
	{InCutscenePAftermath: 0},
	{InCutsceneCRftermath: 0},
	{InCutscene1: 0},
	{InCutscene2: 0},
	{InCutscene3: 0},
	{InCutscene4: 0},
	{InCutscene5: 0},
	{InCutscene6: 0},
	{InCutscene7: 0},
	{InCutscene8: 0},
	{InCutscene9: 0},
	{InCutscene10: 0},
	{InCrackRollCutscene: 0},
	{InDreadRollCutscene: 0},
	{InCrackRollbossCutscene: 0},
	{CarrotinCutscene: 0},
	{Carrotspearpicklespear: 0},
	{PickleSpearupgrade: 0},
	{PickleSpearReady: 0},
	{WeaponToggle: 0},
	{CarrotSpearLemonade: 0},
	{Level1: 0},
	{Level2: 0},
	{Level3: 0},
	{Level4: 0},
	{Level5: 0},
	{ParmaggeddonMovement: 0},
	{ParmaggeddonBossFight: 0},
	{ParmeggeddonParmPowda: 0},
	{ParmaggeddonMeateorite: 0},
	{ParmaggedonAlive: 0},
	{CrackRollBossfight: 0},
	{YeastbeastAftermathToggle: 0},
	{ParmaggeddonAfterMathToggle: 0},
	{CrackRollAfterMathToggle: 0},
	{CrackRollAlive: 0},
	{CrackRollHealth: 0},
	{ParmaggeddonHealth: 0},
	{BreadNaughtBuildProgress: 0},
	{BreadNaughtMinigunCooldown: 0},
	{BreadNaughtMinigunAmmoCount: 0},
	{BreadnaughtWeaponToggle: 0},
	{BreadnaughtMissilecooldown: 0},
	{CrackRollPhase2Alive: 0},
	{DreadRollPhase: 0}
];

self.InstanceType = {
	GreyTileBackGround: class extends self.ITiledBackgroundInstance {},
	Counter: class extends self.ISpriteInstance {},
	EvilBaguette: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Window1: class extends self.ISpriteInstance {},
	Window2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	GoodButters: class extends self.ISpriteInstance {},
	Healthbar: class extends self.ISpriteInstance {},
	Fridge: class extends self.ISpriteInstance {},
	KillBox: class extends self.ISpriteInstance {},
	HealingApple: class extends self.ISpriteInstance {},
	Carrotspear: class extends self.ISpriteInstance {},
	CrackerSpike1: class extends self.ISpriteInstance {},
	CrackerSpike2: class extends self.ISpriteInstance {},
	CrackerSpike3: class extends self.ISpriteInstance {},
	Cookie1: class extends self.ISpriteInstance {},
	Cookie2: class extends self.ISpriteInstance {},
	BreadRoll: class extends self.ISpriteInstance {},
	BreadrollLimiter: class extends self.ISpriteInstance {},
	DashUpgrade: class extends self.ISpriteInstance {},
	SprintUpgrade: class extends self.ISpriteInstance {},
	DJUpgrade: class extends self.ISpriteInstance {},
	EJUpgrade: class extends self.ISpriteInstance {},
	Lemonade: class extends self.ISpriteInstance {},
	LemonadeUpgrade: class extends self.ISpriteInstance {},
	LemonadeShrapnel: class extends self.ISpriteInstance {},
	CheckpointFlag: class extends self.ISpriteInstance {},
	DreadRollBox: class extends self.ISpriteInstance {},
	DreadRoll: class extends self.ISpriteInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	IntroText1: class extends self.ITextInstance {},
	IntroText2: class extends self.ITextInstance {},
	IntroText3: class extends self.ITextInstance {},
	IntroText4: class extends self.ITextInstance {},
	IntroText5: class extends self.ITextInstance {},
	IntroText6: class extends self.ITextInstance {},
	IntroText7: class extends self.ITextInstance {},
	IntroText8: class extends self.ITextInstance {},
	IntroText9: class extends self.ITextInstance {},
	Titlecard: class extends self.ISpriteInstance {},
	Fire: class extends self.ISpriteInstance {},
	BarrierBeam1: class extends self.ISpriteInstance {},
	TutorialText1: class extends self.ITextInstance {},
	TutorialText2: class extends self.ITextInstance {},
	TutorialText3: class extends self.ITextInstance {},
	TutorialText4: class extends self.ITextInstance {},
	TutorialText5: class extends self.ITextInstance {},
	GoodButterTutorialStartBox: class extends self.ISpriteInstance {},
	GoodButtersbox1: class extends self.ITextInstance {},
	GoodButtersBox2: class extends self.ITextInstance {},
	YeastBeast: class extends self.ISpriteInstance {},
	BarrierBeamEmitter1: class extends self.ISpriteInstance {},
	Pantrybackground1: class extends self.ISpriteInstance {},
	PantryPlatforms: class extends self.ISpriteInstance {},
	YeastBeastBarrier: class extends self.ISpriteInstance {},
	YeastBeastRNG: class extends self.ITextInstance {},
	GlazeWaveright: class extends self.ISpriteInstance {},
	GlazeWaveleft: class extends self.ISpriteInstance {},
	YeastBeastMines: class extends self.ISpriteInstance {},
	RightPantryWall: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	YeastBeastSpawnTrigger: class extends self.ISpriteInstance {},
	YeastBeastSpawnBox: class extends self.ISpriteInstance {},
	HealingAppleDialogueBox: class extends self.ISpriteInstance {},
	HealingAppleText: class extends self.ITextInstance {},
	LemonadeDialogueBox: class extends self.ISpriteInstance {},
	LemonadeDialogue: class extends self.ITextInstance {},
	BreadRollDialogueBox: class extends self.ISpriteInstance {},
	BreadRollDialogue: class extends self.ITextInstance {},
	MeleeDialogueBox: class extends self.ISpriteInstance {},
	MeleeUpgrade: class extends self.ISpriteInstance {},
	ButterKnife: class extends self.ISpriteInstance {},
	MeleeDialogue: class extends self.ITextInstance {},
	Cinemabars: class extends self.ISpriteInstance {},
	CheckpointflagCutsceneBoc1: class extends self.ISpriteInstance {},
	CheckpointFlagCutscene1: class extends self.ITextInstance {},
	CFCutscene1Array: class extends self.IArrayInstance {},
	MainMenu: class extends self.ISpriteInstance {},
	ClickBox: class extends self.ITextInstance {},
	PantryMusicTriggerBox: class extends self.ISpriteInstance {},
	Dead: class extends self.ITextInstance {},
	YouR: class extends self.ITextInstance {},
	Restart: class extends self.ITextInstance {},
	Asparagus: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	AsparagusTutorialBox: class extends self.ISpriteInstance {},
	asparagusTutorialText: class extends self.ITextInstance {},
	CheckpointflagCutsceneBoc2: class extends self.ISpriteInstance {},
	CFCutscene2Array: class extends self.IArrayInstance {},
	CheckpointFlagCutscene2: class extends self.ITextInstance {},
	StartButton: class extends self.ISpriteInstance {},
	MainMenuBlackout: class extends self.ISpriteInstance {},
	Shelves: class extends self.ISpriteInstance {},
	BossBlackout: class extends self.ISpriteInstance {},
	TBCText: class extends self.ITextInstance {},
	TBCRestartText: class extends self.ITextInstance {},
	Crosshair: class extends self.ISpriteInstance {},
	PickleSpear: class extends self.ISpriteInstance {},
	PickleSpearUpgrade: class extends self.ISpriteInstance {},
	butterKnifeUI: class extends self.ISpriteInstance {},
	LemonadeUI: class extends self.ISpriteInstance {},
	CheckpointFlagMedical: class extends self.ISpriteInstance {},
	AsparagusHitbox: class extends self.ISpriteInstance {},
	VentBackground: class extends self.ITiledBackgroundInstance {},
	XVent: class extends self.ISpriteInstance {},
	KitchenDecoration1: class extends self.ISpriteInstance {},
	VentBackground2: class extends self.ITiledBackgroundInstance {},
	VentWalls: class extends self.ITilemapInstance {},
	CFCutscene3Array: class extends self.IArrayInstance {},
	CheckpointflagCutsceneBoc3: class extends self.ISpriteInstance {},
	CheckpointFlagCutscene3: class extends self.ITextInstance {},
	VentPlatforms: class extends self.ITilemapInstance {},
	Tomatoes: class extends self.ISpriteInstance {},
	TomatoExplosion: class extends self.ISpriteInstance {},
	CFBooBox: class extends self.ISpriteInstance {},
	CFCutscene4Array: class extends self.IArrayInstance {},
	CheckpointFlagCutscene4: class extends self.ITextInstance {},
	Parmaggedon: class extends self.ISpriteInstance {},
	ParmaggeddonWallBox1: class extends self.ISpriteInstance {},
	ParmaggeddonWallBox2: class extends self.ISpriteInstance {},
	ParmaggeddonWallBox3: class extends self.ISpriteInstance {},
	ParmaggeddonWallBox4: class extends self.ISpriteInstance {},
	ParmaggeddonWallBox5: class extends self.ISpriteInstance {},
	ParmaggeddonWallBox6: class extends self.ISpriteInstance {},
	ParmaggeddonWhipHitbox: class extends self.ISpriteInstance {},
	ParmaggeddonWhipActivationBox: class extends self.ISpriteInstance {},
	MainaraSlipNSlide: class extends self.ISpriteInstance {},
	ParmaggeddonBFToggle: class extends self.ISpriteInstance {},
	Meatball: class extends self.ISpriteInstance {},
	MeatBallLimiter: class extends self.ISpriteInstance {},
	MeatballExplodybox: class extends self.ISpriteInstance {},
	Parmpowda1: class extends self.ISpriteInstance {},
	Parmpowda2: class extends self.ISpriteInstance {},
	Parmpowda3: class extends self.ISpriteInstance {},
	MeateoriteSpawn: class extends self.ISpriteInstance {},
	Meateorite: class extends self.ISpriteInstance {},
	ParmaggedonSpawnBox: class extends self.ISpriteInstance {},
	CFCutscene5Array: class extends self.IArrayInstance {},
	CheckpointFlagCutscene5: class extends self.ITextInstance {},
	VentPlatformsboss: class extends self.ITilemapInstance {},
	VentWallsboss: class extends self.ITilemapInstance {},
	Window3: class extends self.ISpriteInstance {},
	Pea1: class extends self.ISpriteInstance {},
	Pea2: class extends self.ISpriteInstance {},
	Pea3: class extends self.ISpriteInstance {},
	Level2ToggleBox: class extends self.ISpriteInstance {},
	Level3ToggleBox: class extends self.ISpriteInstance {},
	CrackRollEncounterArray: class extends self.IArrayInstance {},
	CrackRollCutsceneToggleBox: class extends self.ISpriteInstance {},
	CrackRollEncounterCutscene: class extends self.ITextInstance {},
	CheckpointFlagCutsceneBoc6: class extends self.ISpriteInstance {},
	CFCutscene6Array: class extends self.IArrayInstance {},
	CheckpointFlagCutscene6: class extends self.ITextInstance {},
	UpgradeWhiteout: class extends self.ISpriteInstance {},
	LemonadeTooltipText: class extends self.ITextInstance {},
	MeleeTooltipText: class extends self.ITextInstance {},
	DashToolTipText: class extends self.ITextInstance {},
	DoubleJumpToolTipText: class extends self.ITextInstance {},
	EnhancedSprintJumpToolTipText: class extends self.ITextInstance {},
	ShortVent: class extends self.ISpriteInstance {},
	LongVent: class extends self.ISpriteInstance {},
	CircleVents: class extends self.ISpriteInstance {},
	RealWater: class extends self.ISpriteInstance {},
	SinkLeft: class extends self.ISpriteInstance {},
	SinkMiddle: class extends self.ISpriteInstance {},
	SinkRight: class extends self.ISpriteInstance {},
	SinkCrack1: class extends self.ISpriteInstance {},
	SinkCrack2: class extends self.ISpriteInstance {},
	SinkCrack3: class extends self.ISpriteInstance {},
	SinkDivider: class extends self.ISpriteInstance {},
	SinkBackground: class extends self.ISpriteInstance {},
	Guck: class extends self.ISpriteInstance {},
	Meatloaf: class extends self.ISpriteInstance {},
	PileofPlates: class extends self.ISpriteInstance {},
	Plate: class extends self.ISpriteInstance {},
	CheckpointFlagYeastBeastAftermath: class extends self.ISpriteInstance {},
	CheckpointFlagParmaggeddonAftermath: class extends self.ISpriteInstance {},
	YeastbeastaftermathTPbox: class extends self.ISpriteInstance {},
	CFYeastBeastAftermathArray: class extends self.IArrayInstance {},
	CheckpointFlagYeastBeastAftermathCutscene: class extends self.ITextInstance {},
	BaguetteParmSpawnBox: class extends self.ISpriteInstance {},
	ParmaggeddonaftermathTPbox: class extends self.ISpriteInstance {},
	CFParmaggeddonAftermathArray: class extends self.IArrayInstance {},
	CheckpointFlagPArmaggeddonAftermathCutscene: class extends self.ITextInstance {},
	BossBlackoutParm: class extends self.ISpriteInstance {},
	CheckpointFlagCrackrollCutsceneboc: class extends self.ISpriteInstance {},
	CFCRCutsceneArray: class extends self.IArrayInstance {},
	CheckpointFlagCrackrollCutscene: class extends self.ITextInstance {},
	CrackRoll: class extends self.ISpriteInstance {},
	CrackrollSpawnBox: class extends self.ISpriteInstance {},
	CrackrollBosfightTpBox: class extends self.ISpriteInstance {},
	BossBlackoutCrackRoll: class extends self.ISpriteInstance {},
	HomelanderEyes: class extends self.ISpriteInstance {},
	CrackRollLimiter: class extends self.ISpriteInstance {},
	HomelanderEyesSpit: class extends self.ISpriteInstance {},
	CrackRock: class extends self.ISpriteInstance {},
	CrackRollClone1: class extends self.ISpriteInstance {},
	CrackRollClone2: class extends self.ISpriteInstance {},
	CrackRollClone3: class extends self.ISpriteInstance {},
	CrackRollPhase2SpawnBox: class extends self.ISpriteInstance {},
	CrackRollSmokeBomb: class extends self.ISpriteInstance {},
	CrackAftermathCutsceneToggleBoc: class extends self.ISpriteInstance {},
	CrackAftermathCutsceneTPBoc: class extends self.ISpriteInstance {},
	CrackAftermathCutsceneTPForCrackBoc: class extends self.ISpriteInstance {},
	CFCrackRollAftermathArray: class extends self.IArrayInstance {},
	CheckpointFlagCrackrollaftermathCutscene: class extends self.ITextInstance {},
	CheckpointFlagCRCutscene: class extends self.ISpriteInstance {},
	Oven: class extends self.ISpriteInstance {},
	GoodButtersDed: class extends self.ISpriteInstance {},
	CheckpointFlagCutsceneBoc7: class extends self.ISpriteInstance {},
	CFCutscene7Array: class extends self.IArrayInstance {},
	CheckpointFlagCutscene7: class extends self.ITextInstance {},
	BreadNoughtObjective: class extends self.ITextInstance {},
	PickleSpearUI: class extends self.ISpriteInstance {},
	PickleSpearTooltipText: class extends self.ITextInstance {},
	CrackRock2: class extends self.ISpriteInstance {},
	CrackRock3: class extends self.ISpriteInstance {},
	Window4: class extends self.ISpriteInstance {},
	Level4Limiters: class extends self.ISpriteInstance {},
	YeastBeastHealthBAar: class extends self.ISpriteInstance {},
	ParmaggeddonHealthBar: class extends self.ISpriteInstance {},
	CrackRollHealthBar: class extends self.ISpriteInstance {},
	Toaster: class extends self.ISpriteInstance {},
	AsbestosCrunch: class extends self.ISpriteInstance {},
	SpringBean: class extends self.ISpriteInstance {},
	Bean: class extends self.ISpriteInstance {},
	Cutscene1: class extends self.ISpriteInstance {},
	Cutscene1Black: class extends self.ISpriteInstance {},
	Cutscene1Black2: class extends self.ISpriteInstance {},
	Cutscene1Black3: class extends self.ISpriteInstance {},
	Cutscene1Black4: class extends self.ISpriteInstance {},
	Cutscene1Black5: class extends self.ISpriteInstance {},
	Cutscene1Black6: class extends self.ISpriteInstance {},
	Cutscene1Blackout: class extends self.ISpriteInstance {},
	BreadNaughtPiece1: class extends self.ISpriteInstance {},
	BreadNaughtPiece2: class extends self.ISpriteInstance {},
	BreadnaughtPiece3: class extends self.ISpriteInstance {},
	BreadnaughtPiece4: class extends self.ISpriteInstance {},
	BossBlackoutBreadNaught: class extends self.ISpriteInstance {},
	BreadNaughtTPBox: class extends self.ISpriteInstance {},
	SinkWater: class extends self.ISpriteInstance {},
	BreadNaught: class extends self.ISpriteInstance {},
	FridgeBreadNaught: class extends self.ISpriteInstance {},
	BreadNaughtMiniguns: class extends self.ISpriteInstance {},
	BreadNaughtMinigunBullet: class extends self.ISpriteInstance {},
	BreadNaughtAmmoCounter: class extends self.ITextInstance {},
	BreadNaughtMissileLauncher: class extends self.ISpriteInstance {},
	BreadNaughtMissile: class extends self.ISpriteInstance {},
	BreadNaughtCrosshair: class extends self.ISpriteInstance {},
	BreadNaughtMissleTracker: class extends self.ISpriteInstance {},
	CrackRollPhase2: class extends self.ISpriteInstance {},
	BossBlackoutDreadRoll: class extends self.ISpriteInstance {},
	CheckpointFlagDRCutscene: class extends self.ISpriteInstance {},
	BreadnaughtDreadrollTpBox: class extends self.ISpriteInstance {},
	CrackRollDreadrollTpBox: class extends self.ISpriteInstance {},
	DreadRollSpawnBox: class extends self.ISpriteInstance {},
	CFCutscene8Array: class extends self.IArrayInstance {},
	Level4EndTPBox: class extends self.ISpriteInstance {},
	CheckpointFlagCutscene8: class extends self.ITextInstance {},
	CFCutscene9Array: class extends self.IArrayInstance {},
	CheckpointFlagCutscene9: class extends self.ITextInstance {},
	CheckPointFlagCutsceneBoc8: class extends self.ISpriteInstance {},
	BossBlackoutBreadnaught2: class extends self.ISpriteInstance {},
	CrackRollPhase2ded: class extends self.ISpriteInstance {},
	CheckpointFlagCutscene10: class extends self.ITextInstance {},
	CFCutscene10Array: class extends self.IArrayInstance {},
	BossBlackoutDreadRoll2: class extends self.ISpriteInstance {},
	DreadRollBoss: class extends self.ISpriteInstance {},
	DreadTenacles: class extends self.ISpriteInstance {},
	DreadRollDREAD: class extends self.ISpriteInstance {},
	DreadRollPhaseProgress: class extends self.ISpriteInstance {},
	DreadRollShardSpawnBox: class extends self.ISpriteInstance {},
	DreadShard: class extends self.ISpriteInstance {},
	FIN: class extends self.ISpriteInstance {},
	ENDBLACK: class extends self.ISpriteInstance {},
	CrackerSpikes: class extends self.ISpriteInstance {},
	Cookies: class extends self.ISpriteInstance {}
}